"""Shared fixtures.

Two build artefacts have to be stood in for so the pure-Python suite runs on
an unbuilt tree: `kubik.const` (generated by Meson from `const.py.in`) and the
GResource bundle holding the compiled Blueprint templates.
"""

from __future__ import annotations

import pathlib
import sys
import types

import pytest


# --- kubik.const stub -------------------------------------------------------

def _ensure_const_stub() -> None:
    if "kubik.const" in sys.modules:
        return
    try:
        import kubik.const  # noqa: F401
        return
    except Exception:
        pass
    module = types.ModuleType("kubik.const")
    module.APP_ID = "land.rob.kubik"
    module.APP_NAME = "Kubik"
    module.VERSION = "test"
    module.PKGDATADIR = ""
    module.LOCALEDIR = ""
    sys.modules["kubik.const"] = module


_ensure_const_stub()


# --- gi version declarations ------------------------------------------------

def _ensure_gi_versions() -> None:
    """Mirror the launcher's single-entry `gi.require_version` block.

    `kubik.in` is the entry point in a real run; under pytest this module is,
    so the declarations belong here.
    """
    try:
        import gi
    except ImportError:
        return
    for namespace, version in (("Gtk", "4.0"), ("Adw", "1"), ("Gdk", "4.0")):
        try:
            gi.require_version(namespace, version)
        except ValueError:
            pass    # optional typelib absent, or already pinned


_ensure_gi_versions()


# --- GResource bundle -------------------------------------------------------

def gresource_available() -> bool:
    """Register the compiled UI bundle if a build produced one.

    Importing `kubik.window` pulls in the `@Gtk.Template` class, which
    resolves its `.ui` out of the GResource bundle at *import* time and raises
    if it is not registered. The bundle is a build artefact
    (blueprint-compiler + glib-compile-resources), so tests that need it skip
    on an unbuilt tree rather than failing the pure-Python suite.

    Both CI paths build before running pytest, so this returning False in CI
    would mean the workflow regressed, not that the tests are meant to skip.
    """
    cached = getattr(gresource_available, "_done", None)
    if cached is not None:
        return cached

    root = pathlib.Path(__file__).resolve().parent.parent
    ok = False
    for name in ("_build", "builddir"):
        path = root / name / "data" / "ui" / "land.rob.kubik.gresource"
        if not path.exists():
            continue
        try:
            from gi.repository import Gio
            Gio.resources_register(Gio.Resource.load(str(path)))
            ok = True
            break
        except Exception:
            continue
    gresource_available._done = ok
    return ok


# --- GSettings schema -------------------------------------------------------

def _ensure_schema() -> None:
    """Compile the schema to a temp dir so `Gio.Settings.new` works.

    The window persists geometry and the selected puzzle through GSettings,
    which refuses to construct against an uninstalled schema. Compiling into a
    scratch directory keeps the tests independent of whether the app has ever
    been installed on the machine.
    """
    import os
    import shutil
    import subprocess
    import tempfile

    compiler = shutil.which("glib-compile-schemas")
    if compiler is None:
        return
    root = pathlib.Path(__file__).resolve().parent.parent
    schema = root / "data" / "land.rob.kubik.gschema.xml"
    if not schema.exists():
        return
    target = pathlib.Path(tempfile.gettempdir()) / "kubik-test-schemas"
    target.mkdir(exist_ok=True)
    shutil.copy(schema, target)
    try:
        subprocess.run([compiler, str(target)], check=True,
                       capture_output=True)
    except subprocess.CalledProcessError:
        return
    existing = os.environ.get("GSETTINGS_SCHEMA_DIR", "")
    parts = [str(target)] + ([existing] if existing else [])
    os.environ["GSETTINGS_SCHEMA_DIR"] = os.pathsep.join(parts)


_ensure_schema()


needs_gresource = pytest.mark.skipif(
    not gresource_available(),
    reason="UI bundle not built; run meson compile first",
)
